annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.93.0.tgz
dateCreated: '2026-02-02T14:58:19.820752Z'
digest: b0f67be6726dea95d15f9c32f8da548b5cbcf91fbf29dcf71e14e02017dd4093
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
