annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-4.87.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-4.87.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-4.87.0.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.87.0.tgz
dateCreated: '2025-12-01T12:14:37.099229Z'
digest: be419b5057041c1dd39d0ec5ee74b77e1e16195dcfd4cbb9e43b818db62e86da
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
